function printfooter(){
    // document.write("<section class=\"bg-bright info contact-sec\">");
    // document.write("	<div class=\"container\">");
    // document.write("		<div class=\"row flex-row-desktop center\">");
    // document.write("			<div class=\"col-md-6 col-sm-6\">");
    // document.write("				<div class=\"iframe-wrapper\">");
    // document.write("						<iframe src=\"https:\/\/www.google.com\/maps\/embed?pb=!1m18!1m12!1m3!1d3806.0652622251696!2d78.37312025018399!3d17.45659020534222!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcb96e22d2253f1%3A0x51c630df2fe85055!2sDeep%20Red%20Ink!5e0!3m2!1sen!2sin!4v1574225075358!5m2!1sen!2sin\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\"><\/iframe>");
    // document.write("				<\/div>");
    // document.write("			<\/div>");
    // document.write("			<div class=\"col-md-6  col-md-offset-3 col-sm-6 col-sm-offset-3\">");
    // document.write("				<div class=\"section-heading mb-magin\">");
    // document.write("					<small>Contact us<\/small>");
    // document.write("					<h2 class=\"title\">Book a free consultation with us<\/h2>");
    // document.write("					<p>Please fill in your details and our team will get in touch with you<\/p>");
    // document.write("				<\/div>");
    // document.write("				<div class=\"form-wrapper\">");
    // document.write("						<form class=\"leadform\" id=\"leadform\" method=\"post\" enctype=\"multipart\/form-data\" action=\"leadgrab.php\">");
    // document.write("						<div class=\"form-group\">");
    // document.write("							<input type=\"text\" class=\"form-control\" name=\"fullname\" id=\"fullname\" value=\"\" placeholder=\"Full Name\" required>");
    // document.write("						<\/div>");
    // document.write("						<div class=\"form-group\">");
    // document.write("							<input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" value=\"\" placeholder=\"Email\" required>");
    // document.write("						<\/div>");
    // document.write("						<div class=\"form-group\">");
    // document.write("							<input type=\"tel\" class=\"form-control intl-tel-input\" name=\"phone\" id=\"phone\" value=\"\"");
    // document.write("								placeholder=\"Phone Number  (10 digits)\" required>");
    // document.write("						<\/div>");
    // document.write("						<div class=\"form-group\">");
    // document.write("							<textarea name=\"message\" class=\"form-control\" id=\"\" cols=\"3\" rows=\"2\" placeholder=\"Message\"><\/textarea>");
    // document.write("						<\/div>");
    // document.write("						<input type=\"hidden\" id=\"leadutmsource\" name=\"leadutmsource\" value=\"\" \/>	");
    // document.write("						<input type=\"hidden\" id=\"leadutmcampaign\" name=\"leadutmcampaign\" value=\"\" \/>		");
    // document.write("						<input type=\"hidden\" id=\"leadutmmedium\" name=\"leadutmmedium\" value=\"\" \/>		");
    // document.write("						<input type=\"hidden\" id=\"leadutmterm\" name=\"leadutmterm\" value=\"\" \/>	");
    // document.write("						<input type=\"hidden\" id=\"leadutmcontent\" name=\"leadutmcontent\" value=\"\" \/>");
    // document.write("                        <input type=\"hidden\" id=\"page\" name=\"page\" value=\"Contact Us\" \/>");
    // document.write("                        <input type=\"hidden\" id=\"active_page\" name=\"active_page\" value=\"\" \/>");
    // document.write("");
    // document.write("						<div class=\"formMessage\"><\/div>");
    // document.write("");
    // document.write("						<button type=\"submit\" class=\"btn btn-brand btn-wide margin- ajaxFormButton formSubmit\">Submit<\/button>");
    // document.write("					<\/form>");
    // document.write("				<\/div>");
    // document.write("			<\/div>");
    // document.write("		<\/div>");
    // document.write("	<\/div>");
    // document.write("<\/section>");
    document.write("<section class=\"bg-dark-full section-padding-half info footer-sec\">");
    document.write("	<div class=\"container\">");
    document.write("		<div class=\"row\">");
    document.write("			<div class=\"col-md-4 col-sm-4 col-xs-12\">");
    document.write("				<ul class=\"list\">");
    document.write("				<li class=\"font-heading list-heading\">Useful links<\/li>");
    document.write("				<li><a href=\".\/about.html\">About<\/a><\/li>");
    document.write("				<li><a href=\".\/course-artificial-intelligence.html\">Courses<\/a><\/li>");
    document.write("				<li><a href=\".\/team.html\">Team<\/a><\/li>");
    document.write("				<li><a href=\".\/contact.html\">Contact Us<\/a><\/li>");
    document.write("				<li><a href=\".\/privacy.html\">Privacy Policy<\/a><\/li>");
    document.write("				<\/ul>");
    document.write("			<\/div>");
    document.write("			<div class=\"col-md-4 col-sm-4 col-xs-12\">");
    document.write("                <ul class=\"list address\">");
    document.write("                <li class=\"font-heading list-heading\">Contact Details<\/li>");
    // document.write("                <li><span class=\"icon\"><strong><i class=\"fas fa-map-marker-alt\"><\/i><\/strong><\/span>First floor, V V one, Kavuri Hills Phase 1, <br>Kavuri Hills, Madhapur, Hyderabad, <br>Telangana 500033<\/li>");
    document.write("                <li><span class=\"icon\"><strong><i class=\"fas fa-map-marker-alt\"><\/i><\/strong><\/span>Recode Minds Pvt Ltd. <br>Unit # 204, 205 & 206, second floor, Bizness Square, Opp. HiTEX Entrance, Jubilee Enclave, HiTEC city, Hyderabad 500081<\/li>");
    // document.write("                <li><span class=\"icon\"><strong><i class=\"fas fa-map-marker-alt\"><\/i><\/strong><\/span>1-1-191\/A, First floor, above Vysya Bank, Chikkadpally, Hyderabad, Telangana, Pin-500020.<\/li>");
    document.write("                <li><span class=\"icon\"><strong><i class=\"fas fa-phone-alt\"><\/i><\/strong><\/span><a href=\"tel:9985500567\">9985500567<\/a><\/li>");
    document.write("                <li><span class=\"icon\"><strong><i class=\"fas fa-envelope\"><\/i><\/strong><\/span><a href=\"mailto:info@recodeminds.com\">info@recodeminds.com<\/a><\/li>");
    document.write("                <\/ul>");    
    document.write("			<\/div>");
    document.write("			<div class=\"clearfix hidden visible-sm visible-xs padding-bottom-20\"><\/div>");
    document.write("			<div class=\"col-md-3 col-md-offset-1 col-sm-4\">");
    document.write("				<ul class=\"list-inline social\">");
    document.write("				<li><a href=\"https://www.facebook.com/RecodeMinds/\" target=\"_blank\"><i class=\"fab fa-facebook-f\"><\/i><\/a><\/li>");
    document.write("				<li><a href=\"https://twitter.com/recode_minds\" target=\"_blank\"><i class=\"fab fa-twitter\"><\/i><\/a><\/li>");
    document.write("				<li><a href=\"https://www.linkedin.com/company/recode-minds/\" target=\"_blank\"><i class=\"fab fa-linkedin-in\"><\/i><\/a><\/li>");
    document.write("				<li><a href=\"https://www.instagram.com/recode.minds/\" target=\"_blank\"><i class=\"fab fa-instagram\"><\/i><\/a><\/li>");
    document.write("				<\/ul>");
    document.write("			<\/div>");
    document.write("		<\/div>");
    document.write("	<\/div>");
    document.write("<\/section>");
    document.write("<footer> ");
    document.write("	<div class=\"container\">");
    document.write("		<p class=\"margin-0 text-bright text-align-center\">&copy; Recode Minds. All rights reserved.<\/p>");
    document.write("	<\/div>");
    document.write("<\/footer>");


    // MODWEL FORM :BEGIN
    document.write("<div class=\"modal fade\" id=\"StartLearning\" role=\"dialog\">");
    document.write("	<div class=\"modal-dialog modal-md\">");
    document.write("		<div class=\"modal-content\">");
    document.write("			<div class=\"modal-header text-align-center\">");
    document.write("				<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;<\/button>");
    document.write("				<h3 class=\"modal-title margin-bottom-10\"><b>Connect with a counselor<\/b><\/h3>");
    document.write("				");
    document.write("			<\/div>");
    document.write("			<div class=\"modal-body\">");
    document.write("				<div class=\"form-container\">");
    document.write("					<form class=\"leadform formSubmit\" id=\"leadform-popUp\" method=\"post\" enctype=\"multipart\/form-data\" action=\"#\">");
    document.write("");
    document.write("						<div class=\"wrapper\">");
    document.write("							<div class=\"form-group\">");
    document.write("								<input type=\"text\" class=\"form-control\" name=\"fullname\" id=\"fullname\" required=\"required\" value=\"\" placeholder=\"Full Name\">");
    document.write("							<\/div>");
    document.write("	");
    document.write("							<div class=\"form-group\">");
    document.write("								<input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" value=\"\" required=\"required\" placeholder=\"Email\">");
    document.write("							<\/div>");
    document.write("	");
    document.write("							<div class=\"form-group\">");
    document.write("								<input type=\"tel\" class=\"form-control intl-tel-input\" name=\"phone\" id=\"phone\"  required=\"required\" value=\"\"");
    document.write("									placeholder=\"Phone Number  (10 digits)\">");
    document.write("							<\/div>");
    document.write("			");
    document.write("	");



    document.write("                            <input type=\"hidden\" id=\"page\" name=\"page\" value=\"Book a free consultation\" \/>");
    document.write("                        <input type=\"hidden\" id=\"active_page_poup\" name=\"active_page\" value=\"\" \/>");
    document.write("");
    document.write("							<div class=\"formMessage\"><\/div>");
    document.write("							<div class=\"btn-container text-align-center\">");
    document.write("								<button type=\"submit\" class=\"btn btn-brand ajaxFormButton formSubmit\">Submit<\/button>");
    document.write("							<\/div>");
    document.write("						<\/div>");
    document.write("					<\/form>");
    document.write("				<\/div>");
    document.write("			<\/div>");
    document.write("		<\/div>");
    document.write("	<\/div>");
    document.write("<\/div>");
    // MODWEL FORM :END
}

