function printheader(){
document.write("<header class=\"main-header homemenu\">");
document.write("	<div class=\"container\">");
document.write("		<div class=\"row\">");
document.write("			<div class=\"col-xs-12\">");
document.write("				<a href=\".\/index.html\" class=\"main-logo\"><img src=\".\/img\/logo-brand.png\" alt=\"Recode\"><\/a>");
document.write("				<div id=\"menu-overlay\" class=\"main-menu-toggle\"><\/div>");
document.write("				<div class=\"mobile-slide\" id=\"mobile-main-menu\">");
document.write("					<div class=\"close-menu main-menu-toggle\"><span class=\"remove\"><\/span><\/div>");
document.write("					<nav class=\"main-menu-items\">");
document.write("        ");
document.write("						<li class=\"link-home\">");
document.write("							<a href=\".\/index.html\">Home<\/a>");
document.write("						<\/li>");
document.write("					");
document.write("						<li class=\"link-about\">");
document.write("							<a href=\".\/about.html\">About<\/a>");
document.write("						<\/li>");
document.write("					");
document.write("						<li class=\"dropdown\ link-courses\">");
document.write("							<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Courses <span class=\"caret\"><\/span><\/a>");
document.write("							<ul class=\"dropdown-menu\">");
document.write("								<li class=\"link-ai\"><a href=\".\/course-artificial-intelligence.html\">Artificial Intelligence<\/a><\/li>		");
document.write("								<li class=\"link-block-chain\"><a href=\".\/course-blockchain-for-business.html\">Blockchain for Business<\/a><\/li>");
document.write("								<li class=\"link-cloud\"><a href=\".\/course-cloud-technologies.html\">Cloud Technologies<\/a><\/li>");
document.write("								<li class=\"link-cyber\"><a href=\".\/course-cyber-security.html\">Cyber Security<\/a><\/li>");
document.write("								<li class=\"link-xr\"><a href=\".\/course-extended-reality.html\">XR - Extended Reality<\/a><\/li>");
document.write("							<\/ul>");
document.write("						<\/li>");
document.write("					");
document.write("						<li class=\"link-team\">");
document.write("							<a href=\".\/team.html\">Team<\/a>");
document.write("						<\/li>");
document.write("	");
document.write("						<li class=\"link-contact\">");
document.write("							<a href=\".\/contact.html\">Contact<\/a>");
document.write("						<\/li>");
document.write("					");
document.write("						<li class=\"link-start-learning\">");
document.write("							<a href=\"#\" data-toggle=\"modal\" data-target=\"#StartLearning\" class=\"btn btn-cta margin-0\">Sign up now<\/a>");
document.write("						<\/li>");
document.write("					");
document.write("					<\/nav>");
document.write("				<\/div>");
document.write("				");
document.write("				<button type=\"button\" class=\"main-menu-toggle btn btn-brand\"><span class=\"glyphicon glyphicon-menu-hamburger\"><\/span> Menu<\/button>");
document.write("				");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/header>	");
document.write("<div id=\"menu-overlay\" class=\"main-menu-toggle\"><\/div>");
}